import {
  BookOpen,
  Paintbrush,
  Moon,
  Blocks,
  type LucideIcon,
} from "lucide-react";

export interface GuideCode {
  /** filename / tab label shown above the snippet */
  label?: string;
  language: string;
  code: string;
}

export interface GuideSection {
  id: string;
  heading: string;
  body?: string[];
  /** one or more code snippets — multiple snippets render as stacked blocks */
  code?: GuideCode | GuideCode[];
  callout?: {
    variant: "tip" | "note" | "warning";
    title: string;
    body: string;
  };
  list?: string[];
  table?: { headers: string[]; rows: string[][] };
}

export interface GuideDef {
  id: string;
  title: string;
  shortTitle: string;
  description: string;
  icon: LucideIcon;
  readingTime: string;
  sections: GuideSection[];
}

export const GUIDES: GuideDef[] = [
  // ---------------------------------------------------------------------------
  {
    id: "installation",
    title: "Installation & Setup",
    shortTitle: "Installation",
    description:
      "Install markaui from npm, wire up Tailwind CSS v4, wrap your app with MarkaUIProvider and render your first component — in Next.js, Vite or plain JavaScript.",
    icon: BookOpen,
    readingTime: "4 min",
    sections: [
      {
        id: "install",
        heading: "1. Install the package",
        body: [
          "MarkaUI ships as a single npm package with ESM + CJS builds, full TypeScript types and the theme stylesheet included. Install it with your favourite package manager:",
        ],
        code: {
          language: "bash",
          code: `npm install markaui

# or
bun add markaui
# or
pnpm add markaui
# or
yarn add markaui`,
        },
        callout: {
          variant: "note",
          title: "What ships in the box",
          body: "ESM + CJS bundles, index.d.ts types, theme.css with all 12 luxury themes, and the MarkaUIProvider — the only peer dependencies are react and react-dom (18+).",
        },
      },
      {
        id: "tailwind",
        heading: "2. Set up Tailwind CSS v4",
        body: [
          "MarkaUI components are styled with Tailwind v4 utility classes and CSS custom-property design tokens. In your global stylesheet, import Tailwind, the MarkaUI theme and the animation utilities:",
        ],
        code: {
          label: "app/globals.css",
          language: "css",
          code: `@import "tailwindcss";
@import "markaui/theme.css";
/* optional but recommended — powers enter/exit animation
   utilities (animate-in, fade-in, zoom-in…) used by overlays */
@import "tw-animate-css";`,
        },
        callout: {
          variant: "tip",
          title: "Zero content-path config",
          body: "Since v1.0.1, markaui/theme.css ships a Tailwind @source directive that auto-registers the component bundle — every utility the components use is generated by your own Tailwind engine. No @source or content array needed.",
        },
      },
      {
        id: "provider-next",
        heading: "3. Wrap your app — Next.js (App Router)",
        body: [
          "Add MarkaUIProvider to your root layout. It carries its own \"use client\" directive, so you can use it directly in a server layout; it applies data-theme and the dark class to <html> and persists the selection to localStorage.",
        ],
        code: {
          label: "app/layout.tsx",
          language: "tsx",
          code: `import type { ReactNode } from "react";
import { MarkaUIProvider } from "markaui";
import "./globals.css";

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <MarkaUIProvider defaultTheme="maroon" defaultMode="light">
          {children}
        </MarkaUIProvider>
      </body>
    </html>
  );
}`,
        },
      },
      {
        id: "provider-vite",
        heading: "4. Or wrap your app — Vite / plain React",
        body: ["The same provider works in any React setup — Vite, Remix or a plain SPA:"],
        code: {
          label: "src/main.tsx",
          language: "tsx",
          code: `import React from "react";
import ReactDOM from "react-dom/client";
import { MarkaUIProvider, Button } from "markaui";
import App from "./App";
import "./index.css"; // contains the Tailwind + theme imports

ReactDOM.createRoot(document.getElementById("root")!).render(
  <React.StrictMode>
    <MarkaUIProvider defaultTheme="emerald">
      <App />
    </MarkaUIProvider>
  </React.StrictMode>
);`,
        },
        callout: {
          variant: "tip",
          title: "Works from plain .jsx too",
          body: "Types ship with the package but they're entirely optional — JavaScript projects can import and use every component the same way, with full editor IntelliSense for free.",
        },
      },
      {
        id: "first-component",
        heading: "5. Render your first component",
        body: ["Import any component from the package root and use it — that's the whole tutorial:"],
        code: {
          language: "tsx",
          code: `import { Button, Card, CardContent, Badge } from "markaui";

export function Welcome() {
  return (
    <Card>
      <CardContent className="space-y-3 p-6">
        <Badge variant="gold">Premium</Badge>
        <h3 className="font-serif text-xl font-bold">Welcome to MarkaUI</h3>
        <Button variant="gold" onClick={() => alert("It works!")}>
          Get started
        </Button>
      </CardContent>
    </Card>
  );
}`,
        },
      },
    ],
  },

  // ---------------------------------------------------------------------------
  {
    id: "theming",
    title: "Theming — Change Themes & Colors",
    shortTitle: "Theming & Colors",
    description:
      "How the token system works, how to switch between the 12 luxury themes at runtime, how to drive them yourself without the provider, and how to create your own palette.",
    icon: Paintbrush,
    readingTime: "6 min",
    sections: [
      {
        id: "how-it-works",
        heading: "How theming works",
        body: [
          "Every color in MarkaUI is a CSS custom property (design token). A theme is just a set of token values applied under a data-theme attribute on <html> — so switching themes is instant, with no re-render and no CSS reload.",
          "Utilities like bg-primary, text-foreground and border-border all read these tokens through Tailwind v4's @theme inline mapping, which is why every component re-colors itself automatically.",
        ],
        code: {
          label: "What a theme looks like",
          language: "css",
          code: `/* markaui/theme.css — excerpt */
[data-theme="maroon"] {
  --primary: #7d1f2e;        /* deep maroon */
  --primary-foreground: #fdf3e7;
  --gold: #d9a94a;           /* luxury accent */
  --background: #fdf8f3;
  --ring: #7d1f2e;
  /* …full token set for surfaces, borders, states… */
}

.dark[data-theme="maroon"] {
  --background: #1a0d10;
  --primary: #e8b4b4;
  /* …dark variants for every token… */
}`,
        },
      },
      {
        id: "provider-theme",
        heading: "Switch themes with the provider",
        body: [
          "Pass defaultTheme to MarkaUIProvider to set the initial palette. The provider writes data-theme=\"<id>\" to <html> and saves the choice to localStorage (key markaui-theme).",
        ],
        code: {
          language: "tsx",
          code: `<MarkaUIProvider defaultTheme="royal">
  <App />
</MarkaUIProvider>`,
        },
        table: {
          headers: ["id", "Theme", "Group"],
          rows: [
            ["maroon", "Maroon & Gold", "Signature"],
            ["wine", "Burgundy & Honey", "Signature"],
            ["rose", "Rose Gold", "Signature"],
            ["royal", "Royal Purple", "Signature"],
            ["emerald", "Emerald & Brass", "Heritage"],
            ["forest", "Forest & Sage", "Heritage"],
            ["teal", "Teal & Copper", "Heritage"],
            ["champagne", "Champagne Bronze", "Heritage"],
            ["cocoa", "Cocoa & Caramel", "Heritage"],
            ["coral", "Coral Terracotta", "Modern"],
            ["plum", "Plum & Mauve", "Modern"],
            ["noir", "Noir & Silver", "Modern"],
          ],
        },
      },
      {
        id: "runtime-theme",
        heading: "Change theme at runtime (useMarkaUI)",
        body: [
          "The useMarkaUI hook exposes the current theme, the full theme list and a setter. Build a theme picker in a few lines:",
        ],
        code: {
          language: "tsx",
          code: `"use client";
import { Button, useMarkaUI } from "markaui";

export function ThemePicker() {
  const { theme, themes, setTheme } = useMarkaUI();

  return (
    <div className="flex flex-wrap gap-2">
      {themes.map((t) => (
        <Button
          key={t.id}
          variant={t.id === theme ? "default" : "ghost"}
          onClick={() => setTheme(t.id)}
        >
          {t.name}
        </Button>
      ))}
    </div>
  );
}`,
        },
        callout: {
          variant: "note",
          title: "No provider? No problem.",
          body: "You can drive themes yourself — the provider only wraps attribute writes: <html data-theme=\"royal\" class=\"dark\">. Every component follows whatever is on <html>.",
        },
      },
      {
        id: "use-colors",
        heading: "Use theme colors in your own markup",
        body: [
          "Because the tokens are plain CSS custom properties, your own elements theme themselves for free. Use the token utilities, or the raw variables in arbitrary values:",
        ],
        code: {
          language: "tsx",
          code: `/* Tailwind token utilities — recommended */
<div className="bg-background text-foreground border-border">
  <span className="text-primary">Primary-colored text</span>
  <span className="bg-gold/15 text-gold-foreground">Gold tinted chip</span>
</div>

/* Arbitrary values — direct token access */
<div className="bg-[var(--gold)] text-[var(--gold-foreground)]">
  Gold banner
</div>`,
        },
      },
      {
        id: "custom-theme",
        heading: "Create your own palette",
        body: [
          "Add a new data-theme block after importing markaui/theme.css and it works everywhere immediately — the theme switcher list comes from useMarkaUI().themes, and custom ids appear in MarkaUIProvider's storage automatically.",
        ],
        code: [
          {
            label: "globals.css",
            language: "css",
            code: `@import "markaui/theme.css";

/* your brand, as a first-class MarkaUI theme */
[data-theme="midnight"] {
  --background: #0b1020;
  --foreground: #e6eaf5;
  --primary: #3b5bdb;
  --primary-foreground: #eef2ff;
  --gold: #f0b429;
  --border: #1f2a4d;
  --ring: #3b5bdb;
  /* copy any tokens you want to override — the rest inherit */
}

.dark[data-theme="midnight"] {
  --primary: #748ffc;
  --background: #060a18;
}`,
          },
          {
            label: "Use it",
            language: "tsx",
            code: `<MarkaUIProvider defaultTheme="midnight">
  <App />
</MarkaUIProvider>`,
          },
        ],
        callout: {
          variant: "warning",
          title: "Keep token names",
          body: "Reuse the exact token names from markaui/theme.css (--primary, --background, --gold…) so every component stays in sync. Only override the values — not the names.",
        },
      },
    ],
  },

  // ---------------------------------------------------------------------------
  {
    id: "dark-mode",
    title: "Dark Mode",
    shortTitle: "Dark Mode",
    description:
      "MarkaUI uses a class-based dark strategy that follows the provider — not the operating system. Toggle it from the hook, drive it manually, and avoid the theme flash on first paint.",
    icon: Moon,
    readingTime: "3 min",
    sections: [
      {
        id: "strategy",
        heading: "Class-based dark strategy",
        body: [
          "markaui/theme.css declares @custom-variant dark (&:is(.dark *)), so dark: utilities respond to the dark class on <html> — exactly what MarkaUIProvider toggles. Your app's dark mode follows your UI, not the user's OS preference.",
        ],
        code: {
          language: "css",
          code: `/* already inside markaui/theme.css — nothing to configure */
@custom-variant dark (&:is(.dark *));

.dark[data-theme="maroon"] {
  --background: #1a0d10;
  --foreground: #f3e4e4;
  /* every token has a dark counterpart */
}`,
        },
      },
      {
        id: "toggle",
        heading: "Toggle from the hook",
        body: ["useMarkaUI exposes mode (\"light\" | \"dark\") and a toggleMode helper:"],
        code: {
          language: "tsx",
          code: `"use client";
import { Button, useMarkaUI } from "markaui";

export function ModeToggle() {
  const { mode, toggleMode } = useMarkaUI();

  return (
    <Button variant="outline" onClick={toggleMode}>
      {mode === "dark" ? "☀️ Light" : "🌙 Dark"}
    </Button>
  );
}`,
        },
        callout: {
          variant: "note",
          title: "Persisted automatically",
          body: "The provider stores the mode in localStorage (markaui-mode) and re-applies it on the next visit.",
        },
      },
      {
        id: "no-flash",
        heading: "Prevent the flash of the wrong theme",
        body: [
          "To avoid a light-mode flash for dark-mode visitors, set the attributes before React hydrates — a tiny inline script in <head> reads the storage keys and applies them pre-paint:",
        ],
        code: {
          language: "tsx",
          code: `// app/layout.tsx — inside <head>
const themeInitScript = \`
(function(){
  try {
    var t = localStorage.getItem('markaui-theme');
    var m = localStorage.getItem('markaui-mode');
    if (t) document.documentElement.setAttribute('data-theme', t);
    if (m === 'dark') {
      document.documentElement.classList.add('dark');
      document.documentElement.style.colorScheme = 'dark';
    }
  } catch (e) {}
})();
\`;

<html lang="en" suppressHydrationWarning>
  <head><script dangerouslySetInnerHTML={{ __html: themeInitScript }} /></head>
  …
</html>`,
        },
        callout: {
          variant: "tip",
          title: "suppressHydrationWarning",
          body: "Keep suppressHydrationWarning on <html> — the inline script mutates attributes before hydration, which is expected and safe.",
        },
      },
    ],
  },

  // ---------------------------------------------------------------------------
  {
    id: "usage",
    title: "Working with Components",
    shortTitle: "Usage",
    description:
      "Import patterns, variants and sizes, overriding styles with className, composing components into products, handling events and controlled state.",
    icon: Blocks,
    readingTime: "5 min",
    sections: [
      {
        id: "imports",
        heading: "Import from the package root",
        body: [
          "Everything is a named export from markaui — the ESM build is tree-shakeable, so your bundler keeps only what you import:",
        ],
        code: {
          language: "tsx",
          code: `import { Button, Card, Dialog, Input } from "markaui";

// two components (Link, Media) are Next.js-specific and live in the
// source repo instead — they wrap next/link and next/image.`,
        },
      },
      {
        id: "variants",
        heading: "Variants & sizes",
        body: [
          "Most components use class-variance-authority under the hood: variant controls the look, size controls the geometry. Available variants differ per component — Button alone ships default, gold, outline, ghost, soft and destructive.",
        ],
        code: {
          language: "tsx",
          code: `<Button variant="default">Default</Button>
<Button variant="gold">Gold — luxury accent</Button>
<Button variant="outline">Outline</Button>
<Button variant="ghost">Ghost</Button>
<Button variant="destructive">Destructive</Button>

<Button size="sm">Small</Button>
<Button size="lg" className="rounded-full">Large pill</Button>`,
        },
      },
      {
        id: "override",
        heading: "Override styles with className",
        body: [
          "Every component merges your className through tailwind-merge, so your classes always win over the defaults — no !important, no wrappers:",
        ],
        code: {
          language: "tsx",
          code: `/* default: rounded-xl px-4 — your rounded-full + w-full replace them */
<Button className="w-full rounded-full">Full-width pill</Button>

<Card className="max-w-md border-gold/40 bg-gold/5">
  <CardContent className="p-6">Premium card</CardContent>
</Card>`,
        },
      },
      {
        id: "compose",
        heading: "Compose into product UI",
        body: [
          "Components are uncontrolled by default but compose cleanly. Here's a small product block putting several pieces together:",
        ],
        code: {
          language: "tsx",
          code: `"use client";
import { useState } from "react";
import { Card, CardContent, Badge, Button, Input, Switch } from "markaui";

export function SubscriptionCard() {
  const [renew, setRenew] = useState(true);
  const [promo, setPromo] = useState("");

  return (
    <Card className="max-w-sm">
      <CardContent className="space-y-4 p-6">
        <div className="flex items-center justify-between">
          <h3 className="font-serif text-lg font-bold">Pro plan</h3>
          <Badge variant="gold">Popular</Badge>
        </div>
        <Input
          value={promo}
          onChange={(e) => setPromo(e.target.value)}
          placeholder="Promo code"
        />
        <div className="flex items-center justify-between text-sm">
          <span>Auto-renew</span>
          <Switch checked={renew} onCheckedChange={setRenew} />
        </div>
        <Button variant="gold" className="w-full">
          Subscribe — $12/mo
        </Button>
      </CardContent>
    </Card>
  );
}`,
        },
        callout: {
          variant: "tip",
          title: "Radix under the hood",
          body: "Overlays (Dialog, Select, Popover, Tooltip…) are built on Radix UI primitives — keyboard navigation, focus trapping and ARIA semantics work out of the box.",
        },
      },
      {
        id: "icons",
        heading: "Icons",
        body: [
          "MarkaUI is icon-agnostic, but the docs and demos use lucide-react. Pass icons as children — components give them the right sizing context:",
        ],
        code: {
          language: "tsx",
          code: `import { Gem, Search } from "lucide-react";

<Button variant="gold">
  <Gem className="size-4" />
  Upgrade
</Button>

<Input icon={<Search className="size-4" />} placeholder="Search…" />`,
        },
      },
    ],
  },
];

export function getGuide(id: string | null | undefined): GuideDef | undefined {
  return GUIDES.find((g) => g.id === id);
}
